# 第9讲：NumPy 基础入门

## 课程简介

**NumPy**（Numerical Python）是 Python 中最重要的**科学计算库**之一，也是数据分析、机器学习等领域的基础工具。

NumPy 的核心是一个强大的**多维数组对象（ndarray）**，它具有以下特点：

- 支持大量的**数学运算**和**矩阵操作**
- 运算速度远快于 Python 原生列表
- 提供丰富的**线性代数、统计、随机数**等功能
- 是 Pandas、Matplotlib、Scikit-learn 等库的基础

在本讲中，我们将从零开始学习 NumPy 的基本用法，为后续的数据分析与科学计算打好基础。

## 1 安装与导入 NumPy

<div class="alert alert-success">

**安装 NumPy**

如果你使用的是 **Anaconda**，NumPy 已经自带安装，无需额外操作。

如果需要手动安装，可以在终端中执行：

```bash
pip install numpy
```

</div>

在使用 NumPy 之前，我们需要先将它导入。按照惯例，通常将 NumPy 简写为 `np`：

In [1]:
import numpy as np

# 查看 NumPy 版本
print('NumPy 版本：', np.__version__)

NumPy 版本： 1.26.4


### <font color='limegreen'><b>技巧与提示</b></font>

`import numpy as np` 是社区约定俗成的写法。使用 `np` 作为缩写可以让代码更简洁，后续我们所有的 NumPy 操作都会通过 `np.xxx` 来调用。

## 2 创建数组

### 2.1 从列表创建数组

NumPy 的核心数据结构是 **ndarray**（N-dimensional array，多维数组）。与 Python 的列表（list）不同，ndarray 中的所有元素必须是**相同的数据类型**，这使得它在数值计算时效率更高。

创建数组最常见的方式是使用 `np.array()` 函数，将一个列表传入即可：

In [2]:
# 从列表创建一维数组
a = np.array([1, 2, 3, 4, 5])
print('一维数组：', a)
print('数据类型：', type(a))

一维数组： [1 2 3 4 5]
数据类型： <class 'numpy.ndarray'>


In [3]:
# 从嵌套列表创建二维数组
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print('二维数组：')
print(b)

二维数组：
[[1 2 3]
 [4 5 6]]


In [4]:
# 创建三维数组
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
print('三维数组：')
print(c)

三维数组：
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 2.2 使用内置函数创建数组

除了从列表创建，NumPy 还提供了许多便捷的函数来创建特殊数组：

In [5]:
# 创建全 0 数组
zeros = np.zeros((2, 3))
print('全0数组：')
print(zeros)
print()

# 创建全 1 数组
ones = np.ones((3, 4))
print('全1数组：')
print(ones)
print()

# 创建指定值填充的数组
full = np.full((2, 3), 7)
print('填充值为7的数组：')
print(full)

全0数组：
[[0. 0. 0.]
 [0. 0. 0.]]

全1数组：
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

填充值为7的数组：
[[7 7 7]
 [7 7 7]]


In [6]:
# np.arange：类似 Python 的 range，但返回数组
arr1 = np.arange(0, 10, 2)    # 起始值0，终止值10（不包含），步长2
print('arange:', arr1)

# np.linspace：在指定范围内生成等间隔的数
arr2 = np.linspace(0, 1, 5)   # 从0到1（包含），共5个数
print('linspace:', arr2)

arange: [0 2 4 6 8]
linspace: [0.   0.25 0.5  0.75 1.  ]


In [7]:
# np.eye：创建单位矩阵
eye = np.eye(3)
print('单位矩阵：')
print(eye)

单位矩阵：
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### <font color='darkorange'><b>动手练习 1</b></font>

#### 题目
请完成以下任务：
1. 使用 `np.linspace` 创建一个包含 **10 个元素**、从 **0 到 5** 的等间隔数组
2. 使用 `np.full` 创建一个 **4×4** 的数组，所有元素值为 **3.14**
3. 将它们分别打印出来

#### 你的答案
请在下方代码单元中完成练习。

In [ ]:
# Write your code here



#### 参考答案

<details>
<summary>点击查看示例代码</summary>

```python
arr_lin = np.linspace(0, 5, 10)
arr_full = np.full((4, 4), 3.14)

print("linspace 数组:")
print(arr_lin)
print("\nfull 数组:")
print(arr_full)
```

</details>

## 3 数组属性

每个 NumPy 数组都有一些重要的属性，帮助我们了解数组的基本信息：

| 属性 | 说明 |
|------|------|
| `shape` | 数组的形状（各维度的大小） |
| `ndim` | 数组的维度数 |
| `size` | 数组的元素总数 |
| `dtype` | 数组元素的数据类型 |

In [8]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print('数组内容：')
print(arr)
print()
print('形状 (shape):', arr.shape)    # (2, 3) —— 2行3列
print('维度 (ndim):', arr.ndim)      # 2 —— 二维数组
print('元素总数 (size):', arr.size)   # 6
print('数据类型 (dtype):', arr.dtype) # int64

数组内容：
[[1 2 3]
 [4 5 6]]

形状 (shape): (2, 3)
维度 (ndim): 2
元素总数 (size): 6
数据类型 (dtype): int64


In [9]:
# 创建数组时可以指定数据类型
arr_float = np.array([1, 2, 3], dtype=float)
print('浮点数组：', arr_float)
print('数据类型：', arr_float.dtype)

# 也可以进行类型转换
arr_int = arr_float.astype(int)
print('转换为整数：', arr_int)

浮点数组： [1. 2. 3.]
数据类型： float64
转换为整数： [1 2 3]


### <font color='darkorange'><b>动手练习 2</b></font>

#### 题目
创建一个 **3×4×2** 的全 1 数组，然后打印它的 `shape`、`ndim`、`size` 和 `dtype`。

#### 你的答案
请在下方代码单元中完成练习。

In [ ]:
# Write your code here



#### 参考答案

<details>
<summary>点击查看示例代码</summary>

```python
arr_ones = np.ones((3, 4, 2))

print("形状 (shape):", arr_ones.shape)
print("维度 (ndim):", arr_ones.ndim)
print("总数 (size):", arr_ones.size)
print("类型 (dtype):", arr_ones.dtype)
```

</details>

## 4 索引与切片

NumPy 数组的索引与切片方式和 Python 列表类似，但在多维数组上更加灵活。

### 4.1 一维数组的索引与切片

一维数组的索引方式与列表完全一致：

In [10]:
arr = np.array([10, 20, 30, 40, 50])

print('第一个元素：', arr[0])      # 10
print('最后一个元素：', arr[-1])    # 50
print('切片 [1:4]：', arr[1:4])    # [20 30 40]
print('步长切片 [::2]：', arr[::2]) # [10 30 50]

第一个元素： 10
最后一个元素： 50
切片 [1:4]： [20 30 40]
步长切片 [::2]： [10 30 50]


### 4.2 多维数组的索引与切片

对于多维数组，可以使用**逗号分隔**的方式指定各维度的索引：

In [11]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print('原始数组：')
print(arr2d)
print()

# 访问单个元素：第2行第3列（索引从0开始）
print('arr2d[1, 2] =', arr2d[1, 2])  # 6

# 访问某一行
print('第2行：', arr2d[1])            # [4 5 6]

# 访问某一列
print('第3列：', arr2d[:, 2])          # [3 6 9]

# 切片：前2行，前2列
print('子矩阵 arr2d[:2, :2]：')
print(arr2d[:2, :2])

原始数组：
[[1 2 3]
 [4 5 6]
 [7 8 9]]

arr2d[1, 2] = 6
第2行： [4 5 6]
第3列： [3 6 9]
子矩阵 arr2d[:2, :2]：
[[1 2]
 [4 5]]


下图说明了二维数组的索引方式。轴0作为行，轴1作为列。
![numpy_axis](figures/numpy_axis.jpg)

### 4.3 布尔索引

我们可以使用**布尔条件**来筛选数组中的元素，这在数据分析中非常常用：

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# 布尔条件会返回一个布尔数组
print('大于5的布尔掩码：', arr > 5)

# 使用布尔数组进行索引
print('大于5的元素：', arr[arr > 5])

# 组合条件（注意：使用 & 表示"且"，| 表示"或"，需要加括号）
print('大于3且小于8的元素：', arr[(arr > 3) & (arr < 8)])

大于5的布尔掩码： [False False False False False  True  True  True  True  True]
大于5的元素： [ 6  7  8  9 10]
大于3且小于8的元素： [4 5 6 7]


### 4.4 花式索引（Fancy Indexing）

可以使用**整数数组**作为索引，一次性选取多个特定位置的元素：

In [13]:
arr = np.array([10, 20, 30, 40, 50])

# 使用索引数组选取第0、2、4个元素
indices = [0, 2, 4]
print('花式索引结果：', arr[indices])  # [10 30 50]

花式索引结果： [10 30 50]


### <font color='darkorange'><b>动手练习 3</b></font>

#### 题目
给定以下数组：

```python
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])
```

请完成以下操作：
1. 取出第 2 行第 3 列的元素
2. 取出第 1 列的所有元素
3. 取出所有大于 40 的元素

#### 你的答案
请在下方代码单元中完成练习。

In [ ]:
data = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

# Write your code here



#### 参考答案

<details>
<summary>点击查看示例代码</summary>

```python
# 1. 取出第 2 行第 3 列的元素 (索引从0开始，故行索引用1，列索引用2)
print("第2行第3列:", data[1, 2])

# 2. 取出第 1 列的所有元素 (列索引用0)
print("第1列所有元素:", data[:, 0])

# 3. 取出所有大于 40 的元素 (布尔索引)
print("大于40的元素:", data[data > 40])
```

</details>

### <font color='cornflowerblue'><b>思考题 1</b></font>

NumPy 数组的切片是**视图（view）**还是**副本（copy）**？也就是说，修改切片后的数组，原数组会受到影响吗？请运行以下代码验证你的想法：

```python
original = np.array([1, 2, 3, 4, 5])
sliced = original[1:4]
sliced[0] = 99
print(original)
```

如果想要一个独立的副本，应该怎么做？请在下方代码单元中验证并思考。

In [ ]:
# Write your code here



#### 参考答案

<details>
<summary>点击查看参考答案</summary>

**结论：NumPy 数组的切片是“视图（view）”。**
这意味着修改切片会直接影响原数组。这与 Python 原生列表（切片会生成新列表）不同，NumPy 这样设计是为了在处理大规模数据时节省内存。

如果想要一个完全独立的副本，需要使用 `.copy()` 方法：

```python
original = np.array([1, 2, 3, 4, 5])
sliced_copy = original[1:4].copy()  # 创建独立副本
sliced_copy[0] = 99
print(original)  # 原数组不会被修改，依然是 [1, 2, 3, 4, 5]
```

</details>

## 5 数组运算

NumPy 最大的优势之一就是支持**向量化运算**（Vectorized Operations），即对数组进行逐元素的运算，无需编写循环。

### 5.1 基本算术运算

两个**形状相同**的数组之间可以直接进行逐元素运算：

In [14]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print('加法：', a + b)    # [11 22 33 44]
print('减法：', a - b)    # [-9 -18 -27 -36]
print('乘法：', a * b)    # [10 40 90 160]
print('除法：', b / a)    # [10. 10. 10. 10.]
print('幂运算：', a ** 2)  # [1 4 9 16]

加法： [11 22 33 44]
减法： [ -9 -18 -27 -36]
乘法： [ 10  40  90 160]
除法： [10. 10. 10. 10.]
幂运算： [ 1  4  9 16]


### 5.2 数组与标量运算

数组和一个标量（单个数字）运算时，标量会自动与数组的每个元素进行运算：

In [15]:
arr = np.array([1, 2, 3, 4, 5])

print('每个元素 × 3：', arr * 3)     # [ 3  6  9 12 15]
print('每个元素 + 10：', arr + 10)    # [11 12 13 14 15]
print('每个元素 / 2：', arr / 2)      # [0.5 1.  1.5 2.  2.5]

每个元素 × 3： [ 3  6  9 12 15]
每个元素 + 10： [11 12 13 14 15]
每个元素 / 2： [0.5 1.  1.5 2.  2.5]


### 5.3 比较运算

比较运算会返回布尔数组：

In [16]:
arr = np.array([1, 2, 3, 4, 5])

print('大于 3：', arr > 3)          # [False False False  True  True]
print('等于 2：', arr == 2)          # [False  True False False False]
print('不等于 4：', arr != 4)        # [ True  True  True False  True]

大于 3： [False False False  True  True]
等于 2： [False  True False False False]
不等于 4： [ True  True  True False  True]


### <font color='limegreen'><b>技巧与提示</b></font>

**向量化运算** 是 NumPy 的核心理念。与使用 `for` 循环逐个处理元素相比，向量化运算的速度可以快 **几十倍甚至上百倍**，因为底层使用了优化的 C 语言代码。

**经验法则：** 在 NumPy 中，尽量避免使用 Python 的 `for` 循环来操作数组！

## 6 常用数学与统计函数

NumPy 提供了大量的数学和统计函数。以下是一些最常用的：

| 函数 | 说明 |
|------|------|
| `np.sum()` | 求和 |
| `np.mean()` | 求均值 |
| `np.std()` | 求标准差 |
| `np.min()` / `np.max()` | 求最小值 / 最大值 |
| `np.argmin()` / `np.argmax()` | 求最小值 / 最大值的索引 |
| `np.sqrt()` | 求平方根 |
| `np.abs()` | 求绝对值 |
| `np.exp()` | 求指数 |
| `np.log()` | 求自然对数 |

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print('求和：', np.sum(arr))        # 55
print('均值：', np.mean(arr))       # 5.5
print('标准差：', np.std(arr))      # 2.8722...
print('最小值：', np.min(arr))      # 1
print('最大值：', np.max(arr))      # 10
print('最大值索引：', np.argmax(arr)) # 9
print('平方根：', np.sqrt(arr))

求和： 55
均值： 5.5
标准差： 2.8722813232690143
最小值： 1
最大值： 10
最大值索引： 9
平方根： [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]


### axis 参数

对于多维数组，可以通过 `axis` 参数指定沿哪个轴进行运算：

- `axis=0`：沿**行方向**（对每一列进行操作）
- `axis=1`：沿**列方向**（对每一行进行操作）

In [18]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print('原始数组：')
print(arr2d)
print()
print('全部元素求和：', np.sum(arr2d))         # 45
print('按列求和 (axis=0)：', np.sum(arr2d, axis=0))  # [12 15 18]
print('按行求和 (axis=1)：', np.sum(arr2d, axis=1))  # [ 6 15 24]
print()
print('按列求均值 (axis=0)：', np.mean(arr2d, axis=0))  # [4. 5. 6.]
print('按行求均值 (axis=1)：', np.mean(arr2d, axis=1))  # [2. 5. 8.]

原始数组：
[[1 2 3]
 [4 5 6]
 [7 8 9]]

全部元素求和： 45
按列求和 (axis=0)： [12 15 18]
按行求和 (axis=1)： [ 6 15 24]

按列求均值 (axis=0)： [4. 5. 6.]
按行求均值 (axis=1)： [2. 5. 8.]


### <font color='darkorange'><b>动手练习 4</b></font>

#### 题目
给定以下成绩数组，每行代表一个学生，每列代表一门科目（语文、数学、英语）：

```python
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [76, 85, 82],
                   [90, 92, 88]])
```

请计算：
1. 每个学生的平均成绩（按行求均值）
2. 每门科目的最高分（按列求最大值）
3. 总分最高的学生是第几个？（提示：先按行求和，再用 `argmax`）

#### 你的答案
请在下方代码单元中完成练习。

In [ ]:
scores = np.array([[85, 90, 78],
                   [92, 88, 95],
                   [76, 85, 82],
                   [90, 92, 88]])

# Write your code here



#### 参考答案

<details>
<summary>点击查看示例代码</summary>

```python
# 1. 每个学生的平均成绩（按行求均值，axis=1）
print("每个学生的平均成绩:", scores.mean(axis=1))

# 2. 每门科目的最高分（按列求最大值，axis=0）
print("每门科目的最高分:", scores.max(axis=0))

# 3. 总分最高的学生是第几个？
totals = scores.sum(axis=1)  # 每个人的总分
best_student_idx = totals.argmax() # 找到最大值的索引
print(f"总分最高的学生是第 {best_student_idx + 1} 个")
```

</details>

## 7 数组变形

### 7.1 reshape

`reshape()` 可以在不改变数据的情况下，改变数组的形状。

**注意：** 变形前后的元素总数必须保持一致。

In [19]:
arr = np.arange(1, 13)  # [1, 2, 3, ..., 12]
print('原始数组：', arr)
print('形状：', arr.shape)
print()

# 变形为 3×4
reshaped = arr.reshape(3, 4)
print('变形为 3×4：')
print(reshaped)
print()

# 使用 -1 自动计算某个维度的大小
reshaped2 = arr.reshape(2, -1)  # 2行，列数自动计算
print('变形为 2×?：')
print(reshaped2)

原始数组： [ 1  2  3  4  5  6  7  8  9 10 11 12]
形状： (12,)

变形为 3×4：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

变形为 2×?：
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### 7.2 flatten 和 ravel

- `ravel()`：将多维数组展平为一维数组，返回**视图**（更节省内存）
- `flatten()`：将多维数组展平为一维数组，返回**副本**

In [53]:
arr = np.arange(12).reshape(3, 4)
print("原数组:")
print(arr)

r = arr.ravel()
f = arr.flatten()

r[0] = 999
print("\n修改 ravel() 结果后，原数组可能被影响:")
print(arr)

f[1] = 888
print("\n修改 flatten() 结果后，原数组不受影响:")
print(arr)

原数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

修改 ravel() 结果后，原数组可能被影响:
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]

修改 flatten() 结果后，原数组不受影响:
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


### 7.3 转置

使用 `.T` 属性或 `np.transpose()` 来转置数组（交换行和列）：

In [21]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print('原始数组（2×3）：')
print(arr)
print()
print('转置后（3×2）：')
print(arr.T)

原始数组（2×3）：
[[1 2 3]
 [4 5 6]]

转置后（3×2）：
[[1 4]
 [2 5]
 [3 6]]


### <font color='darkorange'><b>动手练习 5</b></font>

#### 题目
1. 创建一个包含 1 到 24 的一维数组
2. 将其变形为 **4×6** 的二维数组
3. 再将其变形为 **2×3×4** 的三维数组
4. 最后将其展平回一维数组

#### 你的答案
请在下方代码单元中完成练习。

In [ ]:
# Write your code here



#### 参考答案

<details>
<summary>点击查看示例代码</summary>

```python
# 1. 创建一维数组
arr = np.arange(1, 25)
print("1D 数组:\n", arr)

# 2. 变形为 4x6 二维数组
arr_2d = arr.reshape(4, 6)
print("\n2D 数组:\n", arr_2d)

# 3. 变形为 2x3x4 三维数组
arr_3d = arr_2d.reshape(2, 3, 4)
print("\n3D 数组:\n", arr_3d)

# 4. 展平回一维
arr_flat = arr_3d.flatten()
print("\n展平后的数组:\n", arr_flat)
```

</details>

## 8 广播机制（Broadcasting）

**广播** 是 NumPy 中一个非常强大的机制，它允许不同形状的数组之间进行运算。

广播的基本规则：**两个数组的形状从右往左比较时，要么相等，要么其中一个维度为 1。**

具体来讲：
1. 如果两个数组的维度数不同，在维度较少的数组的形状**前面**补 1
2. 如果两个数组在某个维度上的大小不同，其中一个为 1，则将其**拉伸**到与另一个相同
3. 如果两个数组在某个维度上的大小不同，且都不为 1，则报错

来看几个例子：

In [30]:
# 示例 1：二维数组 + 一维数组
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row = np.array([10, 20, 30])

# row 会被广播到每一行
print('二维数组 + 一维数组：')
print(arr2d + row)

二维数组 + 一维数组：
[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [32]:
# 示例 2：二维数组 + 列向量
col = np.array([[100],
                [200],
                [300]])

# col 会被广播到每一列
print('二维数组 + 列向量：')
print(arr2d + col)

二维数组 + 列向量：
[[101 102 103]
 [204 205 206]
 [307 308 309]]


In [26]:
# 示例 3：利用广播进行标准化（每列减去该列的均值）
data = np.array([[1.0, 2.0, 3.0],
                 [4.0, 5.0, 6.0],
                 [7.0, 8.0, 9.0]])

col_mean = data.mean(axis=0)  # 每列的均值
print('每列均值：', col_mean)

normalized = data - col_mean  # 广播：每列减去对应的均值
print('标准化后：')
print(normalized)

每列均值： [4. 5. 6.]
标准化后：
[[-3. -3. -3.]
 [ 0.  0.  0.]
 [ 3.  3.  3.]]


#### 使用 `np.newaxis` 配合广播

在实际数据处理中，我们经常需要手动增加一个维度，让数组形状满足广播规则。常用方法有：

- `reshape()`
- `np.newaxis`

下面以“每一行减去该行均值”为例。


In [56]:
arr = np.random.randn(4, 3)

print("原数组:")
print(arr)

row_means = arr.mean(axis=1)
print("\n每一行的均值:")
print(row_means)
print("row_means 的形状:", row_means.shape)

# 增加一个维度，使其形状从 (4,) 变成 (4, 1)
row_means_2d = row_means[:, np.newaxis]
print("\n增加维度后的形状:", row_means_2d.shape)

demeaned = arr - row_means_2d
print("\n每一行减去本行均值后的结果:")
print(demeaned)

print("\n处理后每一行的均值:")
print(demeaned.mean(axis=1))


原数组:
[[ 0.26191043  1.38844914 -1.77868382]
 [ 0.36427715 -0.18024421 -0.18360878]
 [ 0.41923366 -0.67740922 -0.47777355]
 [ 0.85022233 -1.14392654 -1.25408504]]

每一行的均值:
[-4.27747520e-02  1.41384664e-04 -2.45316373e-01 -5.15929752e-01]
row_means 的形状: (4,)

增加维度后的形状: (4, 1)

每一行减去本行均值后的结果:
[[ 0.30468518  1.43122389 -1.73590907]
 [ 0.36413577 -0.1803856  -0.18375017]
 [ 0.66455003 -0.43209285 -0.23245718]
 [ 1.36615208 -0.62799679 -0.73815529]]

处理后每一行的均值:
[-7.40148683e-17  0.00000000e+00 -1.85037171e-17 -7.40148683e-17]


这里 `row_means` 原本的形状是 `(4,)`，不能直接与 `(4, 3)` 的数组按行相减。  
通过 `row_means[:, np.newaxis]`，它变成 `(4, 1)`，就可以被广播成 `(4, 3)`。


### <font color='cornflowerblue'><b>思考题 2</b></font>

以下两个数组能否进行广播运算？如果能，结果的形状是什么？

```python
a = np.ones((3, 1))
b = np.ones((1, 4))
c = a + b
```
请先思考，然后运行下方代码验证。

In [ ]:
# Write your code here



#### 参考答案

<details>
<summary>点击查看参考答案</summary>

**结论：能进行广播。运算后结果 `c` 的形状是 `(3, 4)`。**

**原因分析：**
- 数组 `a` 形状是 `(3, 1)`
- 数组 `b` 形状是 `(1, 4)`
- 按照广播机制规则，`a` 的第二维大小为1，会被拉伸为4；`b` 的第一维大小为1，会被拉伸为3。
- 最终两者都在形状 `(3, 4)` 上对齐，完成运算。

验证代码：
```python
a = np.ones((3, 1))
b = np.ones((1, 4))
c = a + b
print("结果形状:", c.shape)
print("计算结果:\n", c)
```

</details>

## 9 数组拼接与拆分

### 9.1 数组拼接

| 函数 | 说明 |
|------|------|
| `np.concatenate()` | 沿指定轴拼接 |
| `np.vstack()` | 垂直方向拼接（按行） |
| `np.hstack()` | 水平方向拼接（按列） |

In [34]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print("沿 axis=0 拼接，相当于纵向增加行:")
print(np.concatenate([a, b], axis=0))

print("\n沿 axis=1 拼接，相当于横向增加列:")
print(np.concatenate([a, b], axis=1))


沿 axis=0 拼接，相当于纵向增加行:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

沿 axis=1 拼接，相当于横向增加列:
[[1 2 5 6]
 [3 4 7 8]]


In [35]:
# 垂直拼接（上下叠起来）
print('vstack（垂直拼接）：')
print(np.vstack([a, b]))
print()

# 水平拼接（左右拼起来）
print('hstack（水平拼接）：')
print(np.hstack([a, b]))

vstack（垂直拼接）：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

hstack（水平拼接）：
[[1 2 5 6]
 [3 4 7 8]]


### 9.2 数组拆分

拆分是拼接的反操作：

In [36]:
arr = np.arange(12).reshape(3, 4)
print("原数组:")
print(arr)

print("\n按列方向拆成 2 份:")
parts = np.split(arr, 2, axis=1)
for i, part in enumerate(parts):
    print(f"第 {i + 1} 份:")
    print(part)

print("\n也可以按索引位置拆分:")
parts = np.split(arr, [1, 3], axis=1)
for i, part in enumerate(parts):
    print(f"第 {i + 1} 份:")
    print(part)


原数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

按列方向拆成 2 份:
第 1 份:
[[0 1]
 [4 5]
 [8 9]]
第 2 份:
[[ 2  3]
 [ 6  7]
 [10 11]]

也可以按索引位置拆分:
第 1 份:
[[0]
 [4]
 [8]]
第 2 份:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
第 3 份:
[[ 3]
 [ 7]
 [11]]


## 10 排序

NumPy 提供了灵活的排序功能：

- `np.sort()`：返回排序后的副本（不修改原数组）
- `np.argsort()`：返回排序后元素的**索引**

In [ ]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6])

print('原始数组：', arr)
print('排序后：', np.sort(arr))       # [1 1 2 3 4 5 6 9]
print('排序索引：', np.argsort(arr))  # [1 3 6 0 2 4 7 5]
print()

# 对二维数组排序
arr2d = np.array([[3, 1, 2],
                  [6, 4, 5]])

print('按行排序（axis=1）：')
print(np.sort(arr2d, axis=1))
print()
print('按列排序（axis=0）：')
print(np.sort(arr2d, axis=0))

In [55]:
# 升序或降序
arr = np.array([3, 1, 4, 2])

print("升序排序:")
print(np.sort(arr))

print("\n降序排序:")
print(np.sort(arr)[::-1])

升序排序:
[1 2 3 4]

降序排序:
[4 3 2 1]


## 11 元素重复

NumPy 还提供了两种常用的重复操作：

- `repeat()`：按元素重复
- `tile()`：把整个数组按指定次数平铺

二者都能生成更大的数组，但重复方式不同。


In [50]:
arr = np.array([1, 2, 3])

print("原数组:")
print(arr)

print("\n每个元素重复 2 次:")
print(arr.repeat(2))

print("\n整个数组平铺 2 次:")
print(np.tile(arr, 2))


原数组:
[1 2 3]

每个元素重复 2 次:
[1 1 2 2 3 3]

整个数组平铺 2 次:
[1 2 3 1 2 3]


In [51]:
arr2d = np.array([[1, 2],
                 [3, 4]])

print("二维数组:")
print(arr2d)

print("\n沿 axis=0 重复每一行:")
print(arr2d.repeat(2, axis=0))

print("\n沿 axis=1 重复每一列:")
print(arr2d.repeat(2, axis=1))

print("\n二维平铺:")
print(np.tile(arr2d, (2, 3)))


二维数组:
[[1 2]
 [3 4]]

沿 axis=0 重复每一行:
[[1 2]
 [1 2]
 [3 4]
 [3 4]]

沿 axis=1 重复每一列:
[[1 1 2 2]
 [3 3 4 4]]

二维平铺:
[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


## 12 随机数生成

`np.random` 模块提供了丰富的随机数生成功能：

| 函数 | 说明 |
|------|------|
| `np.random.rand()` | 生成 [0, 1) 均匀分布随机数 |
| `np.random.randn()` | 生成标准正态分布随机数 |
| `np.random.randint()` | 生成随机整数 |
| `np.random.choice()` | 从数组中随机选取 |
| `np.random.shuffle()` | 随机打乱数组 |
| `np.random.seed()` | 设置随机种子（可复现） |

In [ ]:
# 设置随机种子，保证每次运行结果一致
np.random.seed(42)

# 生成 [0, 1) 之间的均匀分布随机数
print('均匀分布（2×3）：')
print(np.random.rand(2, 3))
print()

# 生成标准正态分布随机数
print('正态分布（2×3）：')
print(np.random.randn(2, 3))
print()

# 生成随机整数
print('随机整数 [1, 10)：', np.random.randint(1, 10, size=5))
print()

# 从数组中随机选取
print('随机选取：', np.random.choice([10, 20, 30, 40, 50], size=3))

### <font color='limegreen'><b>技巧与提示</b></font>

**随机种子（seed）** 的作用是让随机数可以被复现。在科学实验和教学中，设置 `np.random.seed()` 可以确保每次运行代码时产生相同的"随机"结果，方便调试和验证。

### <font color='darkorange'><b>动手练习 6</b></font>

#### 题目
1. 设置随机种子为 **0**
2. 生成一个 **5×5** 的随机整数矩阵，元素范围为 **[1, 100)**
3. 打印这个矩阵
4. 找出矩阵中的最大值和最小值，以及它们所在的位置

#### 你的答案
请在下方代码单元中完成练习。

In [ ]:
# Write your code here



#### 参考答案

<details>
<summary>点击查看示例代码</summary>

```python
np.random.seed(0)
mat = np.random.randint(1, 100, size=(5, 5))

print("随机矩阵:\n", mat)
print("最大值:", mat.max(), " 所在展平位置:", mat.argmax())
print("最小值:", mat.min(), " 所在展平位置:", mat.argmin())
```

</details>

## 13 线性代数基础

NumPy 提供了 `np.linalg` 模块来支持常见的线性代数运算。

### 13.1 矩阵乘法

**注意：** `*` 是逐元素乘法，`@` 或 `np.dot()` 才是矩阵乘法！

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# 逐元素乘法
print('逐元素乘法 A * B：')
print(A * B)
print()

# 矩阵乘法
print('矩阵乘法 A @ B：')
print(A @ B)
print()
print('矩阵乘法 np.dot(A, B)：')
print(np.dot(A, B))

### 13.2 其他线性代数运算

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

# 行列式
print('行列式：', np.linalg.det(A))

# 逆矩阵
print('逆矩阵：')
print(np.linalg.inv(A))

# 验证：A × A的逆 ≈ 单位矩阵
print('A × A⁻¹ ≈ I：')
print(np.round(A @ np.linalg.inv(A)))
print()

# 特征值和特征向量
eigenvalues, eigenvectors = np.linalg.eig(A)
print('特征值：', eigenvalues)
print('特征向量：')
print(eigenvectors)

### <font color='cornflowerblue'><b>思考题 3</b></font>

矩阵乘法 `A @ B` 和 `B @ A` 的结果一样吗？请用代码验证，并思考原因。

请在下方代码单元中验证并思考。

In [ ]:
# Write your code here



#### 参考答案

<details>
<summary>点击查看参考答案</summary>

**结论：结果通常不一样。**
在线性代数中，矩阵乘法**不满足交换律**（即 $A \times B \neq B \times A$）。只有在某些特殊情况下（例如其中一个是单位矩阵，或者两个是对角矩阵等）它们才可能相等。

验证代码：
```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A @ B:\n", A @ B)
print("B @ A:\n", B @ A)
```

</details>

## 14 进阶补充：NumPy 高级数组操作

本节内容对前面 NumPy 基础部分进行适度拓展，有助于理解 NumPy 为什么高效，以及在实际数据处理中如何更灵活地操作数组。

### 14.1 NumPy vs Python 列表：性能对比
NumPy 的核心优势之一是**运算速度快**。让我们来做一个实际的性能对比：

In [49]:
import time

# 创建包含 100 万个元素的列表和数组
size = 1000000
python_list = list(range(size))
numpy_array = np.arange(size)

# 测试 Python 列表：每个元素乘以 2
start = time.time()
result_list = [x * 2 for x in python_list]
time_list = time.time() - start

# 测试 NumPy 数组：每个元素乘以 2
start = time.time()
result_numpy = numpy_array * 2
time_numpy = time.time() - start

print(f'Python 列表用时：{time_list:.4f} 秒')
print(f'NumPy 数组用时：{time_numpy:.6f} 秒')
print(f'NumPy 快了约 {time_list / time_numpy:.0f} 倍！')

Python 列表用时：0.0212 秒
NumPy 数组用时：0.000918 秒
NumPy 快了约 23 倍！


<div class="alert alert-success">

**为什么 NumPy 这么快？**

1. **底层实现**：NumPy 使用 C 语言编写，避免了 Python 解释器的开销
2. **连续内存**：ndarray 中的元素在内存中是连续存储的，而 Python 列表存储的是指向对象的指针
3. **向量化运算**：NumPy 使用 SIMD（单指令多数据）等优化技术，一次处理多个数据

</div>

### 14.2 `ndarray` 的内部机制：数据、形状与跨度

NumPy 的核心对象是 `ndarray`。一个数组不只是保存数据本身，还包含解释这些数据所需的元信息，例如：

- `dtype`：数组元素的数据类型
- `shape`：数组的形状
- `ndim`：数组的维度数量
- `strides`：沿着每个维度移动一个元素时，需要跨过的字节数

理解 `strides` 可以帮助我们理解为什么很多切片操作不会复制数据，而是生成原数组的**视图（view）**。

下图简单地说明了`ndarray`的内部结构。
![ndarray](./figures/ndarray.webp)

In [22]:
arr = np.ones((3, 4), dtype=np.float64)

print("数组形状 shape:", arr.shape)
print("数组维度 ndim:", arr.ndim)
print("元素总数 size:", arr.size)
print("数据类型 dtype:", arr.dtype)
print("跨度 strides:", arr.strides)


数组形状 shape: (3, 4)
数组维度 ndim: 2
元素总数 size: 12
数据类型 dtype: float64
跨度 strides: (32, 8)


在上面的例子中，`float64` 类型的每个元素占 8 个字节。  
数组形状为 `(3, 4)`，因此：

- 沿第 0 维移动一行，需要跨过 `4 × 8 = 32` 个字节
- 沿第 1 维移动一列，需要跨过 `8` 个字节

这就是 `strides` 通常显示为 `(32, 8)` 的原因。


### 14.3 `reshape(order="C"/"F")` 与数组顺序

`reshape()` 可以改变数组形状。除了指定目标形状外，还可以通过 `order` 参数指定读取和填充数据的顺序：

- `order="C"`：按行优先顺序读取和填充，这是 NumPy 默认方式
- `order="F"`：按列优先顺序读取和填充，类似 Fortran 语言中的数组顺序

注意：`order` 影响的是元素被读取和重新排列的逻辑顺序。


In [24]:
arr = np.arange(12)

print("原始一维数组:")
print(arr)

print("\n按 C 顺序 reshape:")
print(arr.reshape((3, 4), order="C"))

print("\n按 F 顺序 reshape:")
print(arr.reshape((3, 4), order="F"))


原始一维数组:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

按 C 顺序 reshape:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

按 F 顺序 reshape:
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


对于大多数初学场景，使用默认的 `order="C"` 即可。  
当处理来自其他语言、底层库或特定矩阵格式的数据时，理解 `C` 顺序和 `F` 顺序会很有帮助。


### 14.4 进阶排序：原地排序、间接排序与部分排序

前面已经学习过 `np.sort()` 和 `np.argsort()`。这里补充几个常用细节：

- `np.sort(arr)`：返回排序后的副本，不改变原数组
- `arr.sort()`：原地排序，会直接修改原数组
- `np.lexsort()`：可以按多个关键字排序
- `np.partition()` / `np.argpartition()`：只关心前若干小或大的元素时更高效


In [41]:
arr = np.array([3, 1, 4, 2])

sorted_arr = np.sort(arr)
print("原数组:", arr)
print("np.sort() 返回的排序副本:", sorted_arr)

arr.sort()
print("arr.sort() 原地排序后的数组:", arr)


原数组: [3 1 4 2]
np.sort() 返回的排序副本: [1 2 3 4]
arr.sort() 原地排序后的数组: [1 2 3 4]


多关键字排序可以使用 `np.lexsort()`。  
需要注意的是，`np.lexsort((key2, key1))` 中，最后一个键 `key1` 是主要排序关键字。


In [43]:
names = np.array(["Alice", "Bob", "Alice", "Bob"])
scores = np.array([90, 85, 95, 80])

# 先按 names 排序；names 相同的情况下，再按 scores 排序
idx = np.lexsort((scores, names))

print("排序索引:")
print(idx)

print("\n排序后的姓名:")
print(names[idx])

print("\n排序后的分数:")
print(scores[idx])


排序索引:
[0 2 3 1]

排序后的姓名:
['Alice' 'Alice' 'Bob' 'Bob']

排序后的分数:
[90 95 80 85]


如果只想找出前几个较小的元素，不一定需要完整排序。  
此时可以使用 `partition()` 或 `argpartition()`。


In [48]:
arr = np.array([7, 2, 9, 1, 5, 8, 3])

print("原数组:")
print(arr)

print("\npartition 后，左边是数组中较小的 3 个元素，右边是较大的 4 个元素。但它们内部不一定有序:")
print(np.partition(arr, 3))

idx = np.argpartition(arr, 3)
print("\nargpartition 返回的索引:")
print(idx)

print("\n按这些索引取出的元素:")
print(arr.take(idx))


原数组:
[7 2 9 1 5 8 3]

完整排序:
[1 2 3 5 7 8 9]

partition 后，左边是数组中较小的 3 个元素，右边是较大的 4 个元素。但它们内部不一定有序:
[2 1 3 5 7 8 9]

argpartition 返回的索引:
[1 3 6 4 0 5 2]

按这些索引取出的元素:
[2 1 3 5 7 8 9]


## 课堂小结

在本讲中，我们学习了 NumPy 的基础知识，下面是重点内容回顾：

| 主题 | 核心内容 |
|------|----------|
| **导入** | `import numpy as np` |
| **创建数组** | `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()` |
| **数组属性** | `shape`, `ndim`, `size`, `dtype` |
| **索引与切片** | 一维索引、多维索引、布尔索引、花式索引 |
| **数组运算** | 逐元素运算（`+`, `-`, `*`, `/`）、向量化思想 |
| **统计函数** | `sum()`, `mean()`, `std()`, `min()`, `max()` + `axis` 参数 |
| **数组变形** | `reshape()`, `flatten()`, `.T` 转置 |
| **广播机制** | 不同形状数组之间的自动扩展运算 |
| **拼接与拆分** | `concatenate()`, `vstack()`, `hstack()`, `split()` |
| **排序** | `np.sort()`, `np.argsort()` |
| **元素重复** | `repeat()`, `tile()` |
| **随机数** | `np.random.rand()`, `randint()`, `seed()` |
| **线性代数** | `@` 矩阵乘法、`np.linalg` 模块 |
| **进阶补充** | 性能优势, `strides`, `ravel()`, `flatten()`, `partition()` |

<div class="alert alert-success">

**进一步学习资源**

- NumPy 官方文档：https://numpy.org/doc/stable/
- NumPy 官方教程：https://numpy.org/doc/stable/user/quickstart.html
- NumPy 速查表（Cheat Sheet）：https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf

</div>

---

*本节课到此结束，感谢大家的学习！如有疑问，请随时提问。*